### PR TITLE
ci: change JIRA project to RDT

### PR DESCRIPTION
**Pull request by kumekay**
RDT Jira project is more relevant than the BSP

### CODE REVIEW

**Comment by kumekay** [comment]
@XDanielPaul FYI, I changed the default branch to `v1` from `releases/v1`

**Review by igrr — APPROVED** [review]

**Comment by XDanielPaul** [comment]
> RDT Jira project is more relevant than the BSP

Thank you, I had it opened, but forgot to create a PR yesterday

**Comment by XDanielPaul** [comment]
> @XDanielPaul FYI, I changed the default branch to `v1` from `releases/v1`

Yep, thanks a lot!

**Comment by XDanielPaul** [comment]
@kumekay Looks good to me, merging!

**Pull request merged**
